-- INSERTION

INSERT INTO bank_solvd.`CREDIT_SUMMARY` (`SALARY`, `PATRIMONY`, `CREDIT_TAKEN`) VALUES ( 1000, 500000, 0);
INSERT INTO bank_solvd.`CREDIT_SUMMARY` (`SALARY`, `PATRIMONY`, `CREDIT_TAKEN`) VALUES ( 1800, 90000, 1);
INSERT INTO bank_solvd.`CREDIT_SUMMARY` (`SALARY`, `PATRIMONY`, `CREDIT_TAKEN`) VALUES ( 1200, 95000, 0);
INSERT INTO bank_solvd.`CREDIT_SUMMARY` (`SALARY`, `PATRIMONY`, `CREDIT_TAKEN`) VALUES ( 1300, 9000, 1);


INSERT INTO bank_solvd.`BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 400000, "9 DE JULIO 2580", "ARGENTINA");
INSERT INTO bank_solvd.`BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 4000, "OCAMPO 250", "BOLIVIA");
INSERT INTO bank_solvd.`BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 666000, "NICARAGUA 230", "ARGENTINA");
INSERT INTO bank_solvd.`BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 300100, "CARABOBO 230", "ARGENTINA");
INSERT INTO bank_solvd.`BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 400000, "OCAMPO 250", "BOLIVIA");
INSERT INTO bank_solvd.`BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 10000000, "PEEP 250", "PERU");
INSERT INTO bank_solvd.`BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 1090000, "PEDRO 250", "PERU");

INSERT INTO bank_solvd.`debit_card` ( `EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( "10/10/2025", 123, "VISA");
INSERT INTO bank_solvd.`credit_card` ( `LIMIT_IN_1_DUE`, `LIMIT_IN_DUES`,`EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( 100000, 10000, "10/10/2026", 123, "MASTERCARD");
INSERT INTO bank_solvd.`debit_card` ( `EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( "11/11/2025", 123, "VISA");
INSERT INTO bank_solvd.`credit_card` ( `LIMIT_IN_1_DUE`, `LIMIT_IN_DUES`,`EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( 100000, 10000, "11/11/2026", 123, "MASTERCARD");
INSERT INTO bank_solvd.`debit_card` ( `EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( "12/12/2025", 123, "VISA");
INSERT INTO bank_solvd.`credit_card` ( `LIMIT_IN_1_DUE`, `LIMIT_IN_DUES`,`EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( 100000, 10000, "12/12/2026", 123, "MASTERCARD");
INSERT INTO bank_solvd.`debit_card` ( `EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( "12/12/2025", 123, "VISA");
INSERT INTO bank_solvd.`credit_card` ( `LIMIT_IN_1_DUE`, `LIMIT_IN_DUES`,`EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( 100000, 10000, "12/12/2026", 123, "MASTERCARD");
INSERT INTO bank_solvd.`debit_card` ( `EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( "12/12/2025", 123, "VISA");
INSERT INTO bank_solvd.`credit_card` ( `LIMIT_IN_1_DUE`, `LIMIT_IN_DUES`,`EXPIRATION_DATE`, `SECURITY_CODE` ,`PROVIDER`) VALUES ( 100000, 10000, "12/12/2026", 123, "MASTERCARD");


INSERT INTO bank_solvd.`SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`, `BALANCE`) VALUES ( 1, 10000);
INSERT INTO bank_solvd.`SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`, `BALANCE`) VALUES ( 2, 10);
INSERT INTO bank_solvd.`SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`, `BALANCE`) VALUES ( 3, 1000);
INSERT INTO bank_solvd.`SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`, `BALANCE`) VALUES ( 4, 90000);
INSERT INTO bank_solvd.`SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`, `BALANCE`) VALUES ( 5, 10);
INSERT INTO bank_solvd.`SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`, `BALANCE`) VALUES ( 6, 109990);

INSERT INTO  bank_solvd.`CHECKING_ACCOUNT` (`CHECKS`, `BALANCE`, `DEBIT_CARD_ID`, `CREDIT_CARD_ID`) VALUES ( 1, 33333, 1,1);
INSERT INTO  bank_solvd.`CHECKING_ACCOUNT` (`CHECKS`, `BALANCE`, `DEBIT_CARD_ID`, `CREDIT_CARD_ID`) VALUES (2, 4444,2,2);
INSERT INTO  bank_solvd.`CHECKING_ACCOUNT` (`CHECKS`, `BALANCE`, `DEBIT_CARD_ID`, `CREDIT_CARD_ID`) VALUES (3, 555,3,3);
INSERT INTO  bank_solvd.`CHECKING_ACCOUNT` (`CHECKS`, `BALANCE`, `DEBIT_CARD_ID`, `CREDIT_CARD_ID`) VALUES (4, 6666666,4,4);
INSERT INTO  bank_solvd.`CHECKING_ACCOUNT` (`CHECKS`, `BALANCE`, `DEBIT_CARD_ID`, `CREDIT_CARD_ID`) VALUES (5, 696969,5,5);


INSERT INTO  bank_solvd.`CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE` ) VALUES ( "17/1/2022","17/9/2022",0.5, 10440);
INSERT INTO  bank_solvd.`CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE`   ) VALUES ( "17/2/2022","17/6/2022",0.5, 30000);
INSERT INTO  bank_solvd.`CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE`   ) VALUES ( "17/3/2022","17/4/2022",0.5, 10200);
INSERT INTO  bank_solvd.`CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE`  ) VALUES ( "17/3/2022","17/12/2022",0.5, 10000);
INSERT INTO  bank_solvd.`CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE` ) VALUES ( "17/4/2022","17/11/2022",0.5, 23000);
INSERT INTO  bank_solvd.`CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE` ) VALUES ( "17/6/2022", "17/10/2022",0.5, 124981290);


INSERT INTO  bank_solvd.`HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "user1", "GugER222333");
INSERT INTO  bank_solvd.`HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "user2", "MARK123");
INSERT INTO  bank_solvd.`HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "user3", "MAK323");
INSERT INTO  bank_solvd.`HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "user4", "MARK123");
INSERT INTO  bank_solvd.`HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "MMwCK", "MAK323");




INSERT INTO  bank_solvd.`CLIENT` (`NAME`, `SURNAME`,`AGE`, `COUNTRY`,  `ADDRESS`, `CREDIT_SUMMARY_ID`, `CERTIFICATE_DEPOSIT_ACCOUNT_ID`, `SAVING_ACCOUNT_ID`, `CHECKING_ACCOUNT_ID`, `OFFICE_ID`,`HOMEBANKING_ID`) VALUES ("GERARD", "GUTIERREZ", 25, "BOLIVIA", "MITRE 330",1,1,1,1,1,1);
INSERT INTO  bank_solvd.`CLIENT` (`NAME`, `SURNAME`,`AGE`, `COUNTRY`,  `ADDRESS`, `CREDIT_SUMMARY_ID`, `CERTIFICATE_DEPOSIT_ACCOUNT_ID`, `SAVING_ACCOUNT_ID`, `CHECKING_ACCOUNT_ID`, `OFFICE_ID`,`HOMEBANKING_ID`) VALUES ("ROMINA", "GARRIDO",  40,"CANADA", "MOTRE 330",2,2,2,2,2,2);
INSERT INTO  bank_solvd.`CLIENT` (`NAME`, `SURNAME`,`AGE`, `COUNTRY`,  `ADDRESS`, `CREDIT_SUMMARY_ID`, `CERTIFICATE_DEPOSIT_ACCOUNT_ID`, `SAVING_ACCOUNT_ID`, `CHECKING_ACCOUNT_ID`, `OFFICE_ID`,`HOMEBANKING_ID`) VALUES ("MARTA", "GARROTE", 38,"PERU", "METRE 330", 3,3,3,3,3,3);
INSERT INTO  bank_solvd.`CLIENT` (`NAME`, `SURNAME`,`AGE`, `COUNTRY`,  `ADDRESS`, `CREDIT_SUMMARY_ID`, `CERTIFICATE_DEPOSIT_ACCOUNT_ID`, `SAVING_ACCOUNT_ID`, `CHECKING_ACCOUNT_ID`, `OFFICE_ID`,`HOMEBANKING_ID`) VALUES ("MARK", "ZUCKERBERG", 20, "US", "FAKE ST. 123",4,4,4,4,4,4);





-- UPDATES

UPDATE  bank_solvd.`CLIENT` SET `COUNTRY` = "ITALIA" WHERE `CLIENT_ID` = 2;
UPDATE  bank_solvd.`CLIENT` SET `ADDRESS` = "TRELLES 1330" WHERE `CLIENT_ID` = 2;

UPDATE  bank_solvd.`CREDIT_SUMMARY` SET `SALARY` = 4000 WHERE `CREDIT_SUMMARY_ID` = 2;
UPDATE  bank_solvd.`CREDIT_SUMMARY` SET `CREDIT_TAKEN` = 1 WHERE `CREDIT_SUMMARY_ID` = 1;

UPDATE  bank_solvd.`BANK_BRANCH_OFFICE` SET `GENERAL_BALANCE` = 350000 WHERE `OFFICE_ID`= 1;

UPDATE  bank_solvd.`SAVING_ACCOUNT` SET `MONTH_WITHDRAWALS` = 3 WHERE `SAVING_ACCOUNT_ID` = 1;
UPDATE  bank_solvd.`CHECKING_ACCOUNT` SET `CHECKS` = 9 WHERE `CHECKING_ACCOUNT_ID` = 1;

UPDATE  bank_solvd.`HOMEBANKING` SET `PASSWORD` = "GugER22563" WHERE `HOMEBANKING_ID` = 1;

-- DELETES
SET FOREIGN_KEY_CHECKS=0;
DELETE FROM  bank_solvd.`CLIENT` WHERE `CLIENT_ID` = 3;
DELETE FROM  bank_solvd.`CLIENT` WHERE `CLIENT_ID` = 2;
DELETE FROM  bank_solvd.`BANK_BRANCH_OFFICE` WHERE `OFFICE_ID`= 2;
DELETE FROM  bank_solvd.`BANK_BRANCH_OFFICE` WHERE `OFFICE_ID`= 3;
DELETE FROM  bank_solvd.`CREDIT_SUMMARY` WHERE `CREDIT_SUMMARY_ID` = 3;
DELETE FROM  bank_solvd.`CREDIT_SUMMARY` WHERE `CREDIT_SUMMARY_ID` = 2;

DELETE FROM  bank_solvd.`SAVING_ACCOUNT` WHERE `SAVING_ACCOUNT_ID` = 2;
DELETE FROM  bank_solvd.`CHECKING_ACCOUNT` WHERE `CHECKING_ACCOUNT_ID` = 2;
DELETE FROM  bank_solvd.`SAVING_ACCOUNT` WHERE `SAVING_ACCOUNT_ID` = 3;
DELETE FROM  bank_solvd.`CHECKING_ACCOUNT` WHERE `CHECKING_ACCOUNT_ID` = 3;
-- ALTER TABLE

ALTER TABLE  bank_solvd.`DEBIT_CARD`
MODIFY `EXPIRATION_DATE`VARCHAR(200);

ALTER TABLE  bank_solvd.`CREDIT_CARD`
ADD COLUMN `HAS CHIP`  TINYINT(1);

ALTER TABLE  bank_solvd.`CREDIT_CARD`
DROP COLUMN `HAS CHIP`;

ALTER TABLE  bank_solvd.`HOMEBANKING`
MODIFY `USERNAME` VARCHAR(200);

-- big statement

SELECT
 bank_solvd.CLIENT.NAME,
 bank_solvd.CLIENT.SURNAME,
 bank_solvd.CHECKING_ACCOUNT.BALANCE as Checking_Balance,
 bank_solvd.CERTIFICATE_DEPOSIT_ACCOUNT.BALANCE as Cert_Dep_Balance,
 bank_solvd.SAVING_ACCOUNT.BALANCE as Saving_Balance
FROM  bank_solvd.CLIENT
JOIN  bank_solvd.`SAVING_ACCOUNT`
ON CLIENT.SAVING_ACCOUNT_ID = SAVING_ACCOUNT.SAVING_ACCOUNT_ID
JOIN  bank_solvd.`CHECKING_ACCOUNT`
ON CLIENT.CHECKING_ACCOUNT_ID = CHECKING_ACCOUNT.CHECKING_ACCOUNT_ID
JOIN  bank_solvd.`CERTIFICATE_DEPOSIT_ACCOUNT`
ON CLIENT.CERTIFICATE_DEPOSIT_ACCOUNT_ID = CERTIFICATE_DEPOSIT_ACCOUNT.CERTIFICATE_DEPOSIT_ACCOUNT_ID;

-- left, right, inner and outer joins

SELECT  bank_solvd.`CREDIT_CARD`.*,
bank_solvd.`CHECKING_ACCOUNT`.CHECKING_ACCOUNT_ID,
bank_solvd.`CHECKING_ACCOUNT`.BALANCE,
bank_solvd.`CHECKING_ACCOUNT`.CHECKS
FROM bank_solvd.`CHECKING_ACCOUNT`
LEFT JOIN  bank_solvd.CREDIT_CARD ON CHECKING_ACCOUNT.CREDIT_CARD_ID = CREDIT_CARD.CREDIT_CARD_ID;

SELECT  bank_solvd.`CREDIT_CARD`.*,
bank_solvd.`CHECKING_ACCOUNT`.CHECKING_ACCOUNT_ID,
bank_solvd.`CHECKING_ACCOUNT`.BALANCE,
bank_solvd.`CHECKING_ACCOUNT`.CHECKS
FROM bank_solvd.`CHECKING_ACCOUNT`
RIGHT JOIN  bank_solvd.CREDIT_CARD ON CHECKING_ACCOUNT.CREDIT_CARD_ID = CREDIT_CARD.CREDIT_CARD_ID;

SELECT  bank_solvd.`DEBIT_CARD`.*,
bank_solvd.`CHECKING_ACCOUNT`.CHECKING_ACCOUNT_ID,
bank_solvd.`CHECKING_ACCOUNT`.BALANCE,
bank_solvd.`CHECKING_ACCOUNT`.CHECKS
FROM bank_solvd.`CHECKING_ACCOUNT`
RIGHT JOIN  bank_solvd.DEBIT_CARD ON CHECKING_ACCOUNT.DEBIT_CARD_ID = DEBIT_CARD.DEBIT_CARD_ID;

SELECT  bank_solvd.HOMEBANKING.USERNAME,  bank_solvd.CLIENT.NAME,  bank_solvd.CLIENT.SURNAME
FROM  bank_solvd.CLIENT
INNER JOIN  bank_solvd.HOMEBANKING ON HOMEBANKING.HOMEBANKING_ID = CLIENT.HOMEBANKING_ID;

-- aggregate functions and group by and without having.

SELECT bank_solvd.CLIENT.CLIENT_ID, COUNT(CLIENT.CHECKING_ACCOUNT_ID) AS TotalCheckingAccounts
FROM bank_solvd.CHECKING_ACCOUNT
JOIN CLIENT ON CHECKING_ACCOUNT.CHECKING_ACCOUNT_ID = CLIENT.CHECKING_ACCOUNT_ID
GROUP BY CLIENT.CLIENT_ID;

SELECT  SUM(CHECKING_ACCOUNT.BALANCE) AS TotalChekingAccountsBalance
FROM bank_solvd.CHECKING_ACCOUNT;



SELECT BANK_BRANCH_OFFICE.COUNTRY, AVG(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS AverageBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY;

SELECT BANK_BRANCH_OFFICE.COUNTRY, MIN(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MinimumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY;

SELECT BANK_BRANCH_OFFICE.COUNTRY, MAX(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MaximumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY;

SELECT BANK_BRANCH_OFFICE.COUNTRY, COUNT(BANK_BRANCH_OFFICE.OFFICE_ID) AS OfficesPerCountry
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY;

-- aggregate functions and group by and with having.

SELECT BANK_BRANCH_OFFICE.COUNTRY, AVG(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS AverageBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING AverageBalancePerCOUNTRY > 150000;

SELECT BANK_BRANCH_OFFICE.COUNTRY, MIN(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MinimumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING BANK_BRANCH_OFFICE.COUNTRY = "ARGENTINA";

SELECT BANK_BRANCH_OFFICE.COUNTRY, MIN(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MinimumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING BANK_BRANCH_OFFICE.COUNTRY = "PERU";

SELECT BANK_BRANCH_OFFICE.COUNTRY, MAX(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MaximumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING BANK_BRANCH_OFFICE.COUNTRY = "BOLIVIA";

SELECT BANK_BRANCH_OFFICE.COUNTRY, COUNT(BANK_BRANCH_OFFICE.OFFICE_ID) AS OfficesPerCountry
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING OfficesPerCountry < 3;


