-- INSERTION



INSERT INTO `CREDIT_SUMMARY` (`SALARY`, `PATRIMONY`, `CREDIT_TAKEN`) VALUES ( 1000, 500000, 0);
INSERT INTO `CREDIT_SUMMARY` (`SALARY`, `PATRIMONY`, `CREDIT_TAKEN`) VALUES ( 1800, 90000, 1);
INSERT INTO `CREDIT_SUMMARY` (`SALARY`, `PATRIMONY`, `CREDIT_TAKEN`) VALUES ( 1200, 95000, 0);
INSERT INTO `CREDIT_SUMMARY` (`SALARY`, `PATRIMONY`, `CREDIT_TAKEN`) VALUES ( 1300, 9000, 1);


INSERT INTO `BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 400000, "9 DE JULIO 2580", "ARGENTINA");
INSERT INTO `BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 4000, "OCAMPO 250", "BOLIVIA");
INSERT INTO `BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 666000, "NICARAGUA 230", "ARGENTINA");
INSERT INTO `BANK_BRANCH_OFFICE` (`GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 300100, "CARABOBO 230", "ARGENTINA");
INSERT INTO `BANK_BRANCH_OFFICE` ( `GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 23000, "OCA 250", "BOLIVIA");
INSERT INTO `BANK_BRANCH_OFFICE` ( `GENERAL_BALANCE`, `ADDRESS` ,`COUNTRY`) VALUES ( 230030, "CAMPO 250", "BOLIVIA");


INSERT INTO `SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`) VALUES ( 1);
INSERT INTO `SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`) VALUES ( 2);
INSERT INTO `SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`) VALUES ( 3);
INSERT INTO `SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`) VALUES ( 4);
INSERT INTO `SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`) VALUES ( 5);
INSERT INTO `SAVING_ACCOUNT` (`MONTH_WITHDRAWALS`) VALUES ( 6);

INSERT INTO `CHECKING_ACCOUNT` (`CHECKS`) VALUES ( 1);
INSERT INTO `CHECKING_ACCOUNT` (`CHECKS`) VALUES (2);
INSERT INTO `CHECKING_ACCOUNT` (`CHECKS`) VALUES (3);
INSERT INTO `CHECKING_ACCOUNT` (`CHECKS`) VALUES (4);
INSERT INTO `CHECKING_ACCOUNT` (`CHECKS`) VALUES (5);


INSERT INTO `CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE` ) VALUES ( "17/1/2022","17/9/2022",0.5, 10440);
INSERT INTO `CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE`   ) VALUES ( "17/2/2022","17/6/2022",0.5, 30000);
INSERT INTO `CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE`   ) VALUES ( "17/3/2022","17/4/2022",0.5, 10200);
INSERT INTO `CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE`  ) VALUES ( "17/3/2022","17/12/2022",0.5, 10000);
INSERT INTO `CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE` ) VALUES ( "17/4/2022","17/11/2022",0.5, 23000);
INSERT INTO `CERTIFICATE_DEPOSIT_ACCOUNT` (`START_DATE`,`FINISH_DATE`, `INTEREST_RATE`, `BALANCE` ) VALUES ( "17/6/2022", "17/10/2022",0.5, 124981290);


INSERT INTO `HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "GGUTIERREZ", "GugER222333");
INSERT INTO `HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "MMZCK", "MARK123");
INSERT INTO `HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "MMwCK", "MAK323");
INSERT INTO `HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "MMZCK", "MARK123");
INSERT INTO `HOMEBANKING`(`USERNAME`, `PASSWORD`) VALUES ( "MMwCK", "MAK323");




INSERT INTO `CLIENT` (`NAME`, `SURNAME`,`AGE`, `COUNTRY`,  `ADDRESS`, `CREDIT_SUMMARY_ID`, `CERTIFICATE_DEPOSIT_ACCOUNT_ID`, `SAVING_ACCOUNT_ID`, `CHECKING_ACCOUNT_ID`, `OFFICE_ID`,`HOMEBANKING_ID`) VALUES ("GERARD", "GUTIERREZ", 25, "BOLIVIA", "MITRE 330",1,1,1,1,1,1);
INSERT INTO `CLIENT` (`NAME`, `SURNAME`,`AGE`, `COUNTRY`,  `ADDRESS`, `CREDIT_SUMMARY_ID`, `CERTIFICATE_DEPOSIT_ACCOUNT_ID`, `SAVING_ACCOUNT_ID`, `CHECKING_ACCOUNT_ID`, `OFFICE_ID`,`HOMEBANKING_ID`) VALUES ("ROMINA", "GARRIDO",  40,"CANADA", "MOTRE 330",2,2,2,2,2,2);
INSERT INTO `CLIENT` (`NAME`, `SURNAME`,`AGE`, `COUNTRY`,  `ADDRESS`, `CREDIT_SUMMARY_ID`, `CERTIFICATE_DEPOSIT_ACCOUNT_ID`, `SAVING_ACCOUNT_ID`, `CHECKING_ACCOUNT_ID`, `OFFICE_ID`,`HOMEBANKING_ID`) VALUES ("MARTA", "GARROTE", 38,"PERU", "METRE 330", 3,3,3,3,3,3);
INSERT INTO `CLIENT` (`NAME`, `SURNAME`,`AGE`, `COUNTRY`,  `ADDRESS`, `CREDIT_SUMMARY_ID`, `CERTIFICATE_DEPOSIT_ACCOUNT_ID`, `SAVING_ACCOUNT_ID`, `CHECKING_ACCOUNT_ID`, `OFFICE_ID`,`HOMEBANKING_ID`) VALUES ("MARK", "ZUCKERBERG", 20, "US", "FAKE ST. 123",4,4,4,4,4,4);





-- UPDATES







UPDATE `CLIENT` SET `COUNTRY` = "ITALIA" WHERE `CLIENT_ID` = 2;
UPDATE `CLIENT` SET `ADDRESS` = "TRELLES 1330" WHERE `CLIENT_ID` = 2;

UPDATE `CREDIT_SUMMARY` SET `SALARY` = 4000 WHERE `CREDIT_SUMMARY_ID` = 2;
UPDATE `CREDIT_SUMMARY` SET `CREDIT_TAKEN` = 1 WHERE `CREDIT_SUMMARY_ID` = 1;

UPDATE `BANK_BRANCH_OFFICE` SET `GENERAL_BALANCE` = 350000 WHERE `OFFICE_ID`= 1;

UPDATE `SAVING_ACCOUNT` SET `MONTH_WITHDRAWALS` = 3 WHERE `SAVING_ACCOUNT_ID` = 1;
UPDATE `CHECKING_ACCOUNT` SET `CHECKS` = 9 WHERE `CHECKING_ACCOUNT_ID` = 1;

UPDATE `HOMEBANKING` SET `PASSWORD` = "GugER22563" WHERE `HOMEBANKING_ID` = 1;

-- DELETES
SET FOREIGN_KEY_CHECKS=0;
DELETE FROM `CLIENT` WHERE `CLIENT_ID` = 3;
DELETE FROM `CLIENT` WHERE `CLIENT_ID` = 2;
DELETE FROM `BANK_BRANCH_OFFICE` WHERE `OFFICE_ID`= 2;
DELETE FROM `BANK_BRANCH_OFFICE` WHERE `OFFICE_ID`= 3;
DELETE FROM `CREDIT_SUMMARY` WHERE `CREDIT_SUMMARY_ID` = 3;
DELETE FROM `CREDIT_SUMMARY` WHERE `CREDIT_SUMMARY_ID` = 2;

DELETE FROM `SAVING_ACCOUNT` WHERE `SAVING_ACCOUNT_ID` = 2;
DELETE FROM `CHECKING_ACCOUNT` WHERE `CHECKING_ACCOUNT_ID` = 1;

-- ALTER TABLE

ALTER TABLE `DEBIT_CARD`
MODIFY `EXPIRATION_DATE`VARCHAR(200);

ALTER TABLE `CREDIT_CARD`
ADD COLUMN `HAS CHIP`  TINYINT(1);

ALTER TABLE `CREDIT_CARD`
DROP COLUMN `HAS CHIP`;

ALTER TABLE `HOMEBANKING`
MODIFY `USERNAME` VARCHAR(200);

-- big statement

SELECT
CLIENT.NAME,
CLIENT.SURNAME,
CHECKING_ACCOUNT.BALANCE,
CERTIFICATE_DEPOSIT_ACCOUNT.BALANCE,
SAVING_ACCOUNT.BALANCE
FROM CLIENT
JOIN `SAVING_ACCOUNT`
ON CLIENT.SAVING_ACCOUNT_ID = SAVING_ACCOUNT.SAVING_ACCOUNT_ID
JOIN `CHECKING_ACCOUNT`
ON CLIENT.CHECKING_ACCOUNT_ID = CHECKING_ACCOUNT.CHECKING_ACCOUNT_ID
JOIN `CERTIFICATE_DEPOSIT_ACCOUNT`
ON CERTIFICATE_DEPOSIT_ACCOUNT.CERTIFICATE_DEPOSIT_ACCOUNT_ID = CLIENT.CERTIFICATE_DEPOSIT_ACCOUNT_ID;

-- left, right, inner and outer joins

SELECT CHECKING_ACCOUNT.*, CLIENT.*
FROM CHECKING_ACCOUNT
LEFT JOIN CREDIT_CARD ON CHECKING_ACCOUNT.CREDIT_CARD_ID = CREDIT_CARD.CREDIT_CARD_ID;

SELECT CHECKING_ACCOUNT.*, DEBIT_CARD.*
FROM DEBIT_CARD
RIGHT JOIN CHECKING_ACCOUNT ON DEBIT_CARD.CHECKING_ACCOUNT = CHECKING_ACCOUNT.CHECKING_ACCOUNT_ID;

SELECT CHECKING_ACCOUNT.*, CREDIT_CARD.*
FROM CREDIT_CARD
RIGHT JOIN CHECKING_ACCOUNT ON CREDIT_CARD.CHECKING_ACCOUNT = CHECKING_ACCOUNT.CHECKING_ACCOUNT_ID;


SELECT HOMEBANKING.USERNAME, CLIENT.NAME, CLIENT.SURNAME
FROM CLIENT
INNER JOIN HOMEBANKING ON HOMEBANKING.CLIENT_ID = CLIENT.CLIENT_ID;

-- aggregate functions and group by and without having.

SELECT CLIENT.CLIENT_ID, COUNT(CLIENT.CHECKING_ACCOUNT_ID) AS TotalCheckingAccounts
FROM CHECKING_ACCOUNT
JOIN CLIENT ON CHECKING_ACCOUNT.CHECKING_ACCOUNT_ID = CLIENT.CHECKING_ACCOUNT_ID
GROUP BY CLIENT.CLIENT_ID;

SELECT  SUM(CHECKING_ACCOUNT.BALANCE) AS TotalCheckingAccountsBalance
FROM CLIENT
GROUP BY CLIENT.OFFICE_ID;


SELECT BANK_BRANCH_OFFICE.COUNTRY, AVG(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS AverageBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY;

SELECT BANK_BRANCH_OFFICE.COUNTRY, MIN(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MinimumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY;

SELECT BANK_BRANCH_OFFICE.COUNTRY, MAX(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MaximumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY;

SELECT BANK_BRANCH_OFFICE.COUNTRY, COUNT(BANK_BRANCH_OFFICE.OFFICE_ID) AS OfficesPerCountry
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY;

-- aggregate functions and group by and with having.

SELECT BANK_BRANCH_OFFICE.COUNTRY, AVG(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS AverageBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING AverageBalancePerCOUNTRY > 150000;

SELECT BANK_BRANCH_OFFICE.COUNTRY, MIN(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MinimumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING BANK_BRANCH_OFFICE.COUNTRY = "ARGENTINA";

SELECT BANK_BRANCH_OFFICE.COUNTRY, MIN(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MinimumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING BANK_BRANCH_OFFICE.COUNTRY = "PERU";

SELECT BANK_BRANCH_OFFICE.COUNTRY, MAX(BANK_BRANCH_OFFICE.GENERAL_BALANCE) AS MaximumBalancePerCOUNTRY
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING BANK_BRANCH_OFFICE.COUNTRY = "BOLIVIA";

SELECT BANK_BRANCH_OFFICE.COUNTRY, COUNT(BANK_BRANCH_OFFICE.OFFICE_ID) AS OfficesPerCountry
FROM BANK_BRANCH_OFFICE
GROUP BY BANK_BRANCH_OFFICE.COUNTRY
HAVING OfficesPerCountry < 3;


